// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: imMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ImDvyMsgInfo;
@class ImDvyMsgList;
@class ImMsg;
@class ImMsgList;
@class ImRefundMsgInfo;
@class ImRefundMsgList;
@class labelInfoMsg;
@class labelMsg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ImMsgRoot : GPBRootObject
@end

#pragma mark - ImMsgBody

typedef GPB_ENUM(ImMsgBody_FieldNumber) {
  ImMsgBody_FieldNumber_MsgType = 1,
  ImMsgBody_FieldNumber_BytesData = 2,
};

/**
 * 总的消息体
 **/
GPB_FINAL @interface ImMsgBody : GPBMessage

@property(nonatomic, readwrite) int32_t msgType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytesData;

@end

#pragma mark - WebClientHeartBeatReq

typedef GPB_ENUM(WebClientHeartBeatReq_FieldNumber) {
  WebClientHeartBeatReq_FieldNumber_UserId = 1,
  WebClientHeartBeatReq_FieldNumber_ImChannel = 2,
};

/**
 * 心跳请求包
 **/
GPB_FINAL @interface WebClientHeartBeatReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 房间号 没有传空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@end

#pragma mark - WebClientHeartBeatResp

typedef GPB_ENUM(WebClientHeartBeatResp_FieldNumber) {
  WebClientHeartBeatResp_FieldNumber_UserId = 1,
  WebClientHeartBeatResp_FieldNumber_ImChannel = 2,
};

/**
 * 心跳回复包
 **/
GPB_FINAL @interface WebClientHeartBeatResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@end

#pragma mark - WebClientJoinReq

typedef GPB_ENUM(WebClientJoinReq_FieldNumber) {
  WebClientJoinReq_FieldNumber_UserId = 1,
  WebClientJoinReq_FieldNumber_Name = 2,
  WebClientJoinReq_FieldNumber_UserImg = 3,
  WebClientJoinReq_FieldNumber_IsMerchant = 4,
};

/**
 * web客户端链接请求 链接socket后发送登录请求
 **/
GPB_FINAL @interface WebClientJoinReq : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 用户昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 用户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userImg;

/** 是否为商户 0-普通用户 1-商户 */
@property(nonatomic, readwrite) int32_t isMerchant;

@end

#pragma mark - WebClientJoinResp

typedef GPB_ENUM(WebClientJoinResp_FieldNumber) {
  WebClientJoinResp_FieldNumber_UserId = 1,
};

/**
 * web客户端链接响应
 **/
GPB_FINAL @interface WebClientJoinResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - WebClientLeaveReq

typedef GPB_ENUM(WebClientLeaveReq_FieldNumber) {
  WebClientLeaveReq_FieldNumber_UserId = 1,
};

/**
 * 断开链接请求 用户断开链接发送请求 断开socket
 **/
GPB_FINAL @interface WebClientLeaveReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - RoomJoinReq

typedef GPB_ENUM(RoomJoinReq_FieldNumber) {
  RoomJoinReq_FieldNumber_ShopId = 1,
  RoomJoinReq_FieldNumber_ImChannel = 2,
  RoomJoinReq_FieldNumber_UserId = 3,
  RoomJoinReq_FieldNumber_FromUserId = 4,
  RoomJoinReq_FieldNumber_ToUserId = 5,
  RoomJoinReq_FieldNumber_Name = 6,
  RoomJoinReq_FieldNumber_UserImg = 7,
};

/**
 * 用户加入房间请求
 **/
GPB_FINAL @interface RoomJoinReq : GPBMessage

/** 商户id 暂时不用 预留字段 */
@property(nonatomic, readwrite) int64_t shopId;

/** 房间号 点客服图标进入房间传空 点击列表进入房间传房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 当前用户id "点击客服图标加入房间时 fromUserId = userId, toUserId = 商家userId" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 创建房间用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/** 创建房间other用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserId;

/** 商家名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 商家logo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userImg;

@end

#pragma mark - RoomJoinResp

typedef GPB_ENUM(RoomJoinResp_FieldNumber) {
  RoomJoinResp_FieldNumber_ShopId = 1,
  RoomJoinResp_FieldNumber_ImChannel = 2,
  RoomJoinResp_FieldNumber_UserId = 3,
  RoomJoinResp_FieldNumber_LabelMsgListArray = 4,
};

/**
 * 用户加入房间响应
 **/
GPB_FINAL @interface RoomJoinResp : GPBMessage

@property(nonatomic, readwrite) int64_t shopId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<labelMsg*> *labelMsgListArray;
/** The number of items in @c labelMsgListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger labelMsgListArray_Count;

@end

#pragma mark - RoomLeaveReq

typedef GPB_ENUM(RoomLeaveReq_FieldNumber) {
  RoomLeaveReq_FieldNumber_ImChannel = 1,
  RoomLeaveReq_FieldNumber_UserId = 2,
};

/**
 * 用户离开房间请求
 **/
GPB_FINAL @interface RoomLeaveReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - RoomLeaveResp

typedef GPB_ENUM(RoomLeaveResp_FieldNumber) {
  RoomLeaveResp_FieldNumber_ImChannel = 1,
  RoomLeaveResp_FieldNumber_UserId = 2,
};

/**
 * 用户离开房间响应
 **/
GPB_FINAL @interface RoomLeaveResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - MsgListReq

typedef GPB_ENUM(MsgListReq_FieldNumber) {
  MsgListReq_FieldNumber_UserId = 1,
};

/**
 * 获取聊天列表请求
 **/
GPB_FINAL @interface MsgListReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - MsgListResp

typedef GPB_ENUM(MsgListResp_FieldNumber) {
  MsgListResp_FieldNumber_UserId = 1,
  MsgListResp_FieldNumber_MsgUnReadCount = 2,
  MsgListResp_FieldNumber_DvyUnReadCount = 3,
  MsgListResp_FieldNumber_RefundUnReadCount = 4,
  MsgListResp_FieldNumber_ImMsgListArray = 5,
};

/**
 * 获取聊天列表响应 点击消息展示聊天列表
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface MsgListResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 未读消息总数 */
@property(nonatomic, readwrite) int32_t msgUnReadCount;

/** 未读发货消息总数 */
@property(nonatomic, readwrite) int32_t dvyUnReadCount;

/** 未读退货消息总数 */
@property(nonatomic, readwrite) int32_t refundUnReadCount;

/** 聊天记录列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMsgList*> *imMsgListArray;
/** The number of items in @c imMsgListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imMsgListArray_Count;

@end

#pragma mark - MsgListDeletedReq

typedef GPB_ENUM(MsgListDeletedReq_FieldNumber) {
  MsgListDeletedReq_FieldNumber_UserId = 1,
  MsgListDeletedReq_FieldNumber_ImChannel = 2,
};

/**
 * 清除聊天列表请求
 **/
GPB_FINAL @interface MsgListDeletedReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@end

#pragma mark - MsgRecordReq

typedef GPB_ENUM(MsgRecordReq_FieldNumber) {
  MsgRecordReq_FieldNumber_ImChannel = 1,
  MsgRecordReq_FieldNumber_UserId = 2,
  MsgRecordReq_FieldNumber_PageNum = 3,
  MsgRecordReq_FieldNumber_PageSize = 4,
};

/**
 * 聊天记录请求 进入房间后拉取聊天记录
 **/
GPB_FINAL @interface MsgRecordReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - MsgRecordResp

typedef GPB_ENUM(MsgRecordResp_FieldNumber) {
  MsgRecordResp_FieldNumber_ImChannel = 1,
  MsgRecordResp_FieldNumber_UserId = 2,
  MsgRecordResp_FieldNumber_ImMsgRecordArray = 3,
};

/**
 * 聊天记录响应
 **/
GPB_FINAL @interface MsgRecordResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 聊天记录数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImMsg*> *imMsgRecordArray;
/** The number of items in @c imMsgRecordArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imMsgRecordArray_Count;

@end

#pragma mark - MsgLabelInfoReq

typedef GPB_ENUM(MsgLabelInfoReq_FieldNumber) {
  MsgLabelInfoReq_FieldNumber_ImLabelId = 1,
};

/**
 * 获取词条详情请求
 **/
GPB_FINAL @interface MsgLabelInfoReq : GPBMessage

@property(nonatomic, readwrite) int64_t imLabelId;

@end

#pragma mark - MsgLabelInfoResp

typedef GPB_ENUM(MsgLabelInfoResp_FieldNumber) {
  MsgLabelInfoResp_FieldNumber_LabelInfoListArray = 1,
};

/**
 * 获取词条详情响应
 **/
GPB_FINAL @interface MsgLabelInfoResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<labelInfoMsg*> *labelInfoListArray;
/** The number of items in @c labelInfoListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger labelInfoListArray_Count;

@end

#pragma mark - ImMsg

typedef GPB_ENUM(ImMsg_FieldNumber) {
  ImMsg_FieldNumber_ImChannel = 1,
  ImMsg_FieldNumber_FromUserId = 2,
  ImMsg_FieldNumber_ToUserId = 3,
  ImMsg_FieldNumber_Content = 4,
  ImMsg_FieldNumber_CreateTime = 5,
  ImMsg_FieldNumber_ReadStatus = 6,
  ImMsg_FieldNumber_ContentType = 7,
};

/**
 * 消息实体
 **/
GPB_FINAL @interface ImMsg : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 用户id userId toUserId 谁对谁说话 需要判断当前用户所属是userId还是toUserId 来展示消息靠左还是靠右 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserId;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/** 已读/未读 */
@property(nonatomic, readwrite) int32_t readStatus;

/** 聊天记录类型 0-普通消息 1-链接 2-图片/视频 */
@property(nonatomic, readwrite) int32_t contentType;

@end

#pragma mark - prodMsg

typedef GPB_ENUM(prodMsg_FieldNumber) {
  prodMsg_FieldNumber_ImChannel = 1,
  prodMsg_FieldNumber_FromUserId = 2,
  prodMsg_FieldNumber_ToUserId = 3,
  prodMsg_FieldNumber_ProdId = 4,
  prodMsg_FieldNumber_ProdName = 5,
  prodMsg_FieldNumber_SkuName = 6,
  prodMsg_FieldNumber_ProdImg = 7,
  prodMsg_FieldNumber_Price = 8,
  prodMsg_FieldNumber_ReadStatus = 9,
  prodMsg_FieldNumber_CreateTime = 10,
};

/**
 * 链接消息实体
 **/
GPB_FINAL @interface prodMsg : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 用户id userId toUserId 谁对谁说话 需要判断当前用户所属是userId还是toUserId 来展示消息靠左还是靠右 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserId;

@property(nonatomic, readwrite) int64_t prodId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *skuName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodImg;

@property(nonatomic, readwrite) int64_t price;

/** 已读/未读 */
@property(nonatomic, readwrite) int32_t readStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

@end

#pragma mark - ImMsgList

typedef GPB_ENUM(ImMsgList_FieldNumber) {
  ImMsgList_FieldNumber_ImChannel = 1,
  ImMsgList_FieldNumber_Name = 2,
  ImMsgList_FieldNumber_UserImg = 3,
  ImMsgList_FieldNumber_FromUserId = 4,
  ImMsgList_FieldNumber_ToUserId = 5,
  ImMsgList_FieldNumber_EndMsg = 6,
  ImMsgList_FieldNumber_ContentType = 7,
  ImMsgList_FieldNumber_EndMsgTime = 8,
  ImMsgList_FieldNumber_UnReadSize = 9,
  ImMsgList_FieldNumber_IsMerchant = 10,
  ImMsgList_FieldNumber_ShopId = 11,
};

/**
 * 聊天列表实体 针对于用户来说，显示的是所有商家的聊天列表（客服的列表）
 *            针对与商家来说，显示的是所有咨询的用互动聊天列表（用户列表）
 **/
GPB_FINAL @interface ImMsgList : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userImg;

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserId;

/** other用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserId;

/** 最后一条消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsg;

/** 消息类型 (0-文本 1-链接) */
@property(nonatomic, readwrite) int32_t contentType;

/** 最后一条消息发送时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsgTime;

/** 未读条数 */
@property(nonatomic, readwrite) int32_t unReadSize;

/** 是否为商家 */
@property(nonatomic, readwrite) int32_t isMerchant;

/** 商户id */
@property(nonatomic, readwrite) int64_t shopId;

@end

#pragma mark - labelMsg

typedef GPB_ENUM(labelMsg_FieldNumber) {
  labelMsg_FieldNumber_ImLabelId = 1,
  labelMsg_FieldNumber_LabelName = 2,
};

/**
 * 词条实体
 **/
GPB_FINAL @interface labelMsg : GPBMessage

@property(nonatomic, readwrite) int64_t imLabelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *labelName;

@end

#pragma mark - labelInfoMsg

typedef GPB_ENUM(labelInfoMsg_FieldNumber) {
  labelInfoMsg_FieldNumber_ImLabelId = 1,
  labelInfoMsg_FieldNumber_LabelInfoTitle = 2,
  labelInfoMsg_FieldNumber_LabelInfoContent = 3,
  labelInfoMsg_FieldNumber_LabelInfoValue = 4,
};

/**
 * 词条详情实体
 **/
GPB_FINAL @interface labelInfoMsg : GPBMessage

@property(nonatomic, readwrite) int64_t imLabelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *labelInfoTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *labelInfoContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *labelInfoValue;

@end

#pragma mark - DvyMsgListReq

typedef GPB_ENUM(DvyMsgListReq_FieldNumber) {
  DvyMsgListReq_FieldNumber_UserId = 1,
  DvyMsgListReq_FieldNumber_PageNum = 2,
  DvyMsgListReq_FieldNumber_PageSize = 3,
};

/**
 * 获取发货列表请求
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface DvyMsgListReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - DvyMsgListResp

typedef GPB_ENUM(DvyMsgListResp_FieldNumber) {
  DvyMsgListResp_FieldNumber_UserId = 1,
  DvyMsgListResp_FieldNumber_MsgUnReadCount = 2,
  DvyMsgListResp_FieldNumber_DvyUnReadCount = 3,
  DvyMsgListResp_FieldNumber_RefundUnReadCount = 4,
  DvyMsgListResp_FieldNumber_ImDvyMsgListsArray = 5,
};

/**
 * 获取发货列表响应
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface DvyMsgListResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 未读消息总数 */
@property(nonatomic, readwrite) int32_t msgUnReadCount;

/** 未读发货消息总数 */
@property(nonatomic, readwrite) int32_t dvyUnReadCount;

/** 未读退货消息总数 */
@property(nonatomic, readwrite) int32_t refundUnReadCount;

/** 发货列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImDvyMsgList*> *imDvyMsgListsArray;
/** The number of items in @c imDvyMsgListsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imDvyMsgListsArray_Count;

@end

#pragma mark - ImDvyMsgList

typedef GPB_ENUM(ImDvyMsgList_FieldNumber) {
  ImDvyMsgList_FieldNumber_ImChannel = 1,
  ImDvyMsgList_FieldNumber_ShopId = 2,
  ImDvyMsgList_FieldNumber_ShopName = 3,
  ImDvyMsgList_FieldNumber_ShopImg = 4,
  ImDvyMsgList_FieldNumber_EndMsg = 5,
  ImDvyMsgList_FieldNumber_UnReadSize = 6,
  ImDvyMsgList_FieldNumber_EndMsgTime = 7,
};

/**
 * 发货列表实体
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImDvyMsgList : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 商户id */
@property(nonatomic, readwrite) int64_t shopId;

/** 商户名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shopName;

/** 商户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shopImg;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsg;

/** 未读消息数 */
@property(nonatomic, readwrite) int32_t unReadSize;

/** 创建时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsgTime;

@end

#pragma mark - ImDvyMsgInfoReq

typedef GPB_ENUM(ImDvyMsgInfoReq_FieldNumber) {
  ImDvyMsgInfoReq_FieldNumber_ImChannelId = 1,
  ImDvyMsgInfoReq_FieldNumber_UserId = 2,
  ImDvyMsgInfoReq_FieldNumber_PageNum = 3,
  ImDvyMsgInfoReq_FieldNumber_PageSize = 4,
};

/**
 * 发货消息详情列表
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImDvyMsgInfoReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - ImDvyMsgInfoResp

typedef GPB_ENUM(ImDvyMsgInfoResp_FieldNumber) {
  ImDvyMsgInfoResp_FieldNumber_ImChannelId = 1,
  ImDvyMsgInfoResp_FieldNumber_UserId = 2,
  ImDvyMsgInfoResp_FieldNumber_ImDvyMsgInfoListArray = 5,
};

/**
 * 发货消息详情列表响应
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImDvyMsgInfoResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImDvyMsgInfo*> *imDvyMsgInfoListArray;
/** The number of items in @c imDvyMsgInfoListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imDvyMsgInfoListArray_Count;

@end

#pragma mark - ImDvyMsgInfo

typedef GPB_ENUM(ImDvyMsgInfo_FieldNumber) {
  ImDvyMsgInfo_FieldNumber_UserId = 1,
  ImDvyMsgInfo_FieldNumber_OrderNumber = 2,
  ImDvyMsgInfo_FieldNumber_ProdName = 3,
  ImDvyMsgInfo_FieldNumber_ProdCount = 4,
  ImDvyMsgInfo_FieldNumber_CreateTime = 5,
  ImDvyMsgInfo_FieldNumber_DvyOrderNumber = 6,
};

/**
 * 发货消息详情实体
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImDvyMsgInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 订单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNumber;

/** 商品名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *prodName;

/** 商品总件数 */
@property(nonatomic, readwrite) int32_t prodCount;

/** 发送时日 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/** 快递单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *dvyOrderNumber;

@end

#pragma mark - RefundMsgListReq

typedef GPB_ENUM(RefundMsgListReq_FieldNumber) {
  RefundMsgListReq_FieldNumber_UserId = 1,
  RefundMsgListReq_FieldNumber_PageNum = 2,
  RefundMsgListReq_FieldNumber_PageSize = 3,
};

/**
 * 退货列表请求
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface RefundMsgListReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - RefundMsgListResp

typedef GPB_ENUM(RefundMsgListResp_FieldNumber) {
  RefundMsgListResp_FieldNumber_UserId = 1,
  RefundMsgListResp_FieldNumber_MsgUnReadCount = 2,
  RefundMsgListResp_FieldNumber_DvyUnReadCount = 3,
  RefundMsgListResp_FieldNumber_RefundUnReadCount = 4,
  RefundMsgListResp_FieldNumber_ImRefundMsgListsArray = 5,
};

/**
 * 退货列表响应
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface RefundMsgListResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 未读消息总数 */
@property(nonatomic, readwrite) int32_t msgUnReadCount;

/** 未读发货消息总数 */
@property(nonatomic, readwrite) int32_t dvyUnReadCount;

/** 未读退货消息总数 */
@property(nonatomic, readwrite) int32_t refundUnReadCount;

/** 发货列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImRefundMsgList*> *imRefundMsgListsArray;
/** The number of items in @c imRefundMsgListsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imRefundMsgListsArray_Count;

@end

#pragma mark - ImRefundMsgList

typedef GPB_ENUM(ImRefundMsgList_FieldNumber) {
  ImRefundMsgList_FieldNumber_ImChannel = 1,
  ImRefundMsgList_FieldNumber_ShopId = 2,
  ImRefundMsgList_FieldNumber_ShopName = 3,
  ImRefundMsgList_FieldNumber_ShopImg = 4,
  ImRefundMsgList_FieldNumber_EndMsg = 5,
  ImRefundMsgList_FieldNumber_UnReadSize = 6,
  ImRefundMsgList_FieldNumber_EndMsgTime = 7,
};

/**
 * 退货列表实体
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImRefundMsgList : GPBMessage

/** 房间号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannel;

/** 商户id */
@property(nonatomic, readwrite) int64_t shopId;

/** 商户名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shopName;

/** 商户头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shopImg;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsg;

/** 未读消息数 */
@property(nonatomic, readwrite) int32_t unReadSize;

/** 创建时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endMsgTime;

@end

#pragma mark - ImRefundMsgInfoReq

typedef GPB_ENUM(ImRefundMsgInfoReq_FieldNumber) {
  ImRefundMsgInfoReq_FieldNumber_ImChannelId = 1,
  ImRefundMsgInfoReq_FieldNumber_UserId = 2,
  ImRefundMsgInfoReq_FieldNumber_PageNum = 3,
  ImRefundMsgInfoReq_FieldNumber_PageSize = 4,
};

/**
 * 退货详情请求
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImRefundMsgInfoReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - ImRefundMsgInfoResp

typedef GPB_ENUM(ImRefundMsgInfoResp_FieldNumber) {
  ImRefundMsgInfoResp_FieldNumber_ImChannelId = 1,
  ImRefundMsgInfoResp_FieldNumber_UserId = 2,
  ImRefundMsgInfoResp_FieldNumber_ImRefundMsgInfoArray = 3,
};

/**
 * 退货消息详情列表响应
 * 修改日期 2025-02-27（发货、退款信息推送）
 **/
GPB_FINAL @interface ImRefundMsgInfoResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ImRefundMsgInfo*> *imRefundMsgInfoArray;
/** The number of items in @c imRefundMsgInfoArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imRefundMsgInfoArray_Count;

@end

#pragma mark - ImRefundMsgInfo

typedef GPB_ENUM(ImRefundMsgInfo_FieldNumber) {
  ImRefundMsgInfo_FieldNumber_UserId = 1,
  ImRefundMsgInfo_FieldNumber_OrderNumber = 2,
  ImRefundMsgInfo_FieldNumber_RefundId = 3,
  ImRefundMsgInfo_FieldNumber_RefundAmount = 4,
  ImRefundMsgInfo_FieldNumber_ProdName = 5,
  ImRefundMsgInfo_FieldNumber_ProdCount = 6,
  ImRefundMsgInfo_FieldNumber_CreateTime = 7,
  ImRefundMsgInfo_FieldNumber_RefundType = 8,
  ImRefundMsgInfo_FieldNumber_RefundStatus = 9,
  ImRefundMsgInfo_FieldNumber_ShopName = 10,
  ImRefundMsgInfo_FieldNumber_ReturnPostalCode = 11,
  ImRefundMsgInfo_FieldNumber_Tel = 12,
  ImRefundMsgInfo_FieldNumber_ReturnProvince = 13,
  ImRefundMsgInfo_FieldNumber_ReturnCity = 14,
  ImRefundMsgInfo_FieldNumber_ReturnArea = 15,
  ImRefundMsgInfo_FieldNumber_ReturnAddress = 16,
};

/**
 * 退货消息详情实体
 * 修改日期 2025-02-27（发货、退款信息推送）
 * 修改日期 2025-03-04（新增退货地址 10-16）
 **/
GPB_FINAL @interface ImRefundMsgInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 订单号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNumber;

/** 退货子订单id 详情查询id */
@property(nonatomic, readwrite) int64_t refundId;

/** 返金金额 */
@property(nonatomic, readwrite) int64_t refundAmount;

/** 商品名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *prodName;

/** 商品总件数 */
@property(nonatomic, readwrite) int32_t prodCount;

/** 发送时日 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/** 返金类型 (仅退款 退货退款) */
@property(nonatomic, readwrite) int32_t refundType;

/** 退货状态 */
@property(nonatomic, readwrite) int32_t refundStatus;

/** 商户名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shopName;

/** 邮政编码（退货） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnPostalCode;

/** 联系方式（退货） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tel;

/** 店铺所在省份（退货） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnProvince;

/** 店铺所在城市（退货） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnCity;

/** 店铺所在区域（退货） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnArea;

/** 店铺详细地址(退货) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *returnAddress;

@end

#pragma mark - DvyListDeleteReq

typedef GPB_ENUM(DvyListDeleteReq_FieldNumber) {
  DvyListDeleteReq_FieldNumber_ImChannelId = 1,
  DvyListDeleteReq_FieldNumber_UserId = 2,
  DvyListDeleteReq_FieldNumber_PageNum = 3,
  DvyListDeleteReq_FieldNumber_PageSize = 4,
};

/**
 * 删除发货列表请求
 * 修改日期 2025-03-05（新增删除发货列表请求）
 **/
GPB_FINAL @interface DvyListDeleteReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - DvyListDeleteResp

typedef GPB_ENUM(DvyListDeleteResp_FieldNumber) {
  DvyListDeleteResp_FieldNumber_ImChannelId = 1,
  DvyListDeleteResp_FieldNumber_UserId = 2,
  DvyListDeleteResp_FieldNumber_PageNum = 3,
  DvyListDeleteResp_FieldNumber_PageSize = 4,
  DvyListDeleteResp_FieldNumber_ImDvyMsgList = 5,
  DvyListDeleteResp_FieldNumber_MsgUnReadCount = 6,
  DvyListDeleteResp_FieldNumber_DvyUnReadCount = 7,
  DvyListDeleteResp_FieldNumber_RefundUnReadCount = 8,
};

/**
 * 删除发货列表响应
 * 修改日期 2025-03-05（新增删除发货列表响应）
 **/
GPB_FINAL @interface DvyListDeleteResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 当前查询的总页数 */
@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, strong, null_resettable) ImDvyMsgList *imDvyMsgList;
/** Test to see if @c imDvyMsgList has been set. */
@property(nonatomic, readwrite) BOOL hasImDvyMsgList;

/** 未读消息总数 */
@property(nonatomic, readwrite) int32_t msgUnReadCount;

/** 未读发货消息总数 */
@property(nonatomic, readwrite) int32_t dvyUnReadCount;

/** 未读退货消息总数 */
@property(nonatomic, readwrite) int32_t refundUnReadCount;

@end

#pragma mark - RefundListDeleteReq

typedef GPB_ENUM(RefundListDeleteReq_FieldNumber) {
  RefundListDeleteReq_FieldNumber_ImChannelId = 1,
  RefundListDeleteReq_FieldNumber_UserId = 2,
  RefundListDeleteReq_FieldNumber_PageNum = 3,
  RefundListDeleteReq_FieldNumber_PageSize = 4,
};

/**
 * 删除退货列表请求
 * 修改日期 2025-03-05（新增删除退货列表请求）
 **/
GPB_FINAL @interface RefundListDeleteReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - RefundListDeleteResp

typedef GPB_ENUM(RefundListDeleteResp_FieldNumber) {
  RefundListDeleteResp_FieldNumber_ImChannelId = 1,
  RefundListDeleteResp_FieldNumber_UserId = 2,
  RefundListDeleteResp_FieldNumber_PageNum = 3,
  RefundListDeleteResp_FieldNumber_PageSize = 4,
  RefundListDeleteResp_FieldNumber_ImRefundMsgList = 5,
  RefundListDeleteResp_FieldNumber_MsgUnReadCount = 6,
  RefundListDeleteResp_FieldNumber_DvyUnReadCount = 7,
  RefundListDeleteResp_FieldNumber_RefundUnReadCount = 8,
};

/**
 * 删除退货列表响应
 * 修改日期 2025-03-05（新增删除退货列表响应）
 **/
GPB_FINAL @interface RefundListDeleteResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imChannelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** 当前查询的总页数 */
@property(nonatomic, readwrite) int32_t pageNum;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, strong, null_resettable) ImRefundMsgList *imRefundMsgList;
/** Test to see if @c imRefundMsgList has been set. */
@property(nonatomic, readwrite) BOOL hasImRefundMsgList;

/** 未读消息总数 */
@property(nonatomic, readwrite) int32_t msgUnReadCount;

/** 未读发货消息总数 */
@property(nonatomic, readwrite) int32_t dvyUnReadCount;

/** 未读退货消息总数 */
@property(nonatomic, readwrite) int32_t refundUnReadCount;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
